-- ============================================================================
-- Virtual Member System for SORI
-- Purpose: Enable artists to be real members with AI-driven activities
-- ============================================================================

-- 1. Add new columns to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS member_type TEXT DEFAULT 'user';
-- 'user': Regular member (human login)
-- 'artist': Artist virtual member (AI-driven)

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS artist_browse_id TEXT UNIQUE;
-- YouTube Music browse_id for artists

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;
-- Blue checkmark badge

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ai_persona JSONB;
-- AI persona data generated by Gemini

-- 2. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_profiles_member_type ON profiles(member_type);
CREATE INDEX IF NOT EXISTS idx_profiles_artist_browse_id ON profiles(artist_browse_id);

-- 3. Comment for documentation
COMMENT ON COLUMN profiles.member_type IS 'user=regular member, artist=AI-driven virtual member';
COMMENT ON COLUMN profiles.artist_browse_id IS 'YouTube Music artist browse_id for virtual members';
COMMENT ON COLUMN profiles.is_verified IS 'Blue verification badge';
COMMENT ON COLUMN profiles.ai_persona IS 'Gemini-generated persona for AI behavior';

-- 4. Allow text-only posts (for AI artist posts without song attachment)
ALTER TABLE posts ALTER COLUMN video_id DROP NOT NULL;
ALTER TABLE posts ALTER COLUMN title DROP NOT NULL;
ALTER TABLE posts ALTER COLUMN artist DROP NOT NULL;
ALTER TABLE posts ALTER COLUMN cover_url DROP NOT NULL;

-- 5. Add post_type column for differentiating music shares from text posts
ALTER TABLE posts ADD COLUMN IF NOT EXISTS post_type TEXT DEFAULT 'music';
-- 'music': Traditional music share post with video_id
-- 'text': Text-only post (AI artist updates, thoughts, etc.)

COMMENT ON COLUMN posts.post_type IS 'music=song share, text=text-only post';
